### ISSUE TITLE
Cannot run `create-dynamodb-tables.js`

### ISSUE THREAD

**Issue by gbouv** [near/near-contract-helper#656]
Running the script `/app/script/create-dynamodb-tables.js` fails with the following error:

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'aws-sdk/clients/dynamodb'
Require stack:
- /app/local_dynamo.js
- /app/scripts/create-dynamodb-tables.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/local_dynamo.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/local_dynamo.js', '/app/scripts/create-dynamodb-tables.js' ]
}
```

cc @andy-haynes

**Comment by gbouv** [comment]
Oh no my bad, I built the docker image using the `Dockerfile` file, instead of using `Dockerfile.app`. When I rebuild it using the later, it works just fine. Sorry for the noise
